# Generated by Django 3.0.14 on 2021-12-28 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=300)),
                ('rating', models.IntegerField()),
                ('pub_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['comments', 'pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('recipe_type', models.CharField(max_length=30)),
                ('view_count', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('rating', models.ManyToManyField(to='recipes.Rating')),
            ],
            options={
                'ordering': ['recipe_type', 'view_count'],
            },
        ),
    ]
