# Generated by Django 3.0.14 on 2022-01-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220101_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='categoryId',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='mainImageId',
            new_name='mainImage',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='shortDescription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
