# Generated by Django 3.0.14 on 2022-01-02 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220101_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['create_date', 'view_count']},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='comments',
            new_name='commentText',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='rating',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
