# Generated by Django 3.0.14 on 2022-01-03 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220102_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='mainImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.RecipeImage'),
        ),
    ]
