# Generated by Django 3.0.14 on 2022-01-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20220106_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
