# Generated by Django 3.0.14 on 2022-01-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
